Laboratorios_Unidad1/Lab03_MVC_Hinojosa/Lab03_MVC_Hinojosa/Models/ClsBillete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab03_MVC_Hinojosa.Models
{
    public class ClsBillete
    {
        public decimal monto { get; set; }
        public int b100 { get; set; }
        public int b50 { get; set; }
        public int b20 { get; set; }
        public int b10 { get; set; }

        public int m5 { get; set; }
        public int m2 { get; set; }
        public int m1 { get; set; }
        public int m050 { get; set; }
        public int m020 { get; set; }
        public int m010 { get; set; }
        public int m005 { get; set; }
        public int m002 { get; set; }
        public int m001 { get; set; }

        public int totalBilletes { get; set; }
        public int totalMonedas { get; set; }
    }
}

Laboratorios_Unidad1/Lab03_MVC_Hinojosa/Lab03_MVC_Hinojosa/Controllers/BilleteController.cs
using Lab03_MVC_Hinojosa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab03_MVC_Hinojosa.Controllers
{
    public class BilleteController : Controller
    {
        // GET: Billete
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CalcularDenominacion(ClsBillete billete)
        {

            int Cantidad = (int)Math.Round(billete.monto * 100);

            int cant100, cant50, cant20, cant10;
            int res100, res50, res20, res10;

            int m5, m2, m1, m050, m020, m010, m005, m002, m001;
            int res5, res2, res1, res050, res020, res010, res005, res002;

            cant100 = Cantidad / 10000;    
            res100 = Cantidad % 10000;

            cant50 = res100 / 5000;
            res50 = res100 % 5000;

            cant20 = res50 / 2000;
            res20 = res50 % 2000;

            cant10 = res20 / 1000;
            res10 = res20 % 1000;


            m5 = res10 / 500;
            res5 = res10 % 500;

            m2 = res5 / 200;
            res2 = res5 % 200;

            m1 = res2 / 100;
            res1 = res2 % 100;

            m050 = res1 / 50;
            res050 = res1 % 50;

            m020 = res050 / 20;
            res020 = res050 % 20;

            m010 = res020 / 10;
            res010 = res020 % 10;

            m005 = res010 / 5;
            res005 = res010 % 5;

            m002 = res005 / 2;
            res002 = res005 % 2;

            m001 = res002;

            billete.b100 = cant100;
            billete.b50 = cant50;
            billete.b20 = cant20;
            billete.b10 = cant10;

            billete.m5 = m5;
            billete.m2 = m2;
            billete.m1 = m1;
            billete.m050 = m050;
            billete.m020 = m020;
            billete.m010 = m010;
            billete.m005 = m005;
            billete.m002 = m002;
            billete.m001 = m001;

            billete.totalBilletes = billete.b100 + billete.b50 + billete.b20 + billete.b10;

            billete.totalMonedas = billete.m5 + billete.m2 + billete.m1 + billete.m050 +
                       billete.m020 + billete.m010 + billete.m005 +
                       billete.m002 + billete.m001;

            return View(billete);
        }
    }
}

Laboratorios_Unidad1/Lab03_MVC_Hinojosa/Lab03_MVC_Hinojosa/Views/Billete/CalcularDenominacion.cshtml
@model Lab03_MVC_Hinojosa.Models.ClsBillete
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CalcularDenominacion</title>
</head>
<body>
    <div>
        <center>
            <h1>Dispesandor de Billetes - Christian Dennis Hinojosa Mucho</h1>
            <br /><br />
            @using (Html.BeginForm("CalcularDenominacion", "Billete", FormMethod.Post))
            {
                <p>
                    @Html.LabelFor(model => model.monto, "Total S/. ")
                    @Html.EditorFor(model => model.monto)
                    @Html.ValidationMessageFor(model => model.monto)

                    <br /><br />
                    <button class="btn-primary">Calcular</button>
                    <br /><br />
                          <div>

                              <p><b>Cantidad de Billetes: </b>@Model.totalBilletes</p>

                              <p><b>Billete de 100: </b>@Model.b100</p>
                              <p><b>Billete de 50: </b>@Model.b50</p>
                              <p><b>Billete de 20: </b>@Model.b20</p>
                              <p><b>Billete de 10: </b>@Model.b10</p>

                              <p><b>Cantidad de Monedas: </b>@Model.totalMonedas</p>

                              <p><b>Moneda de 5: </b>@Model.m5</p>
                              <p><b>Moneda de 2: </b>@Model.m2</p>
                              <p><b>Moneda de 1: </b>@Model.m1</p>
                              <p><b>Moneda de 0.50: </b>@Model.m050</p>
                              <p><b>Moneda de 0.20: </b>@Model.m020</p>
                              <p><b>Moneda de 0.10: </b>@Model.m010</p>
                              <p><b>Moneda de 0.05: </b>@Model.m005</p>
                              <p><b>Moneda de 0.02: </b>@Model.m002</p>
                              <p><b>Moneda de 0.01: </b>@Model.m001</p>

                          </div>

                </p>
            }
        </center>
    </div>
</body>
</html>