Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Models/ClsOperaciones.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab01.MVC_Hinojosa.Models
{
    public class ClsOperaciones
    {
        public double numero1 { get; set; }
        public double numero2 { get; set; }
        public string tipo { get; set; } 
        public double resultado { get; set; }
    }
}

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Models/ClsPersona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab01.MVC_Hinojosa.Models
{
    public class ClsPersona
    {
        public string apellido {  get; set; }
        public string nombres { get; set; }
        public string email { get; set; }
        public int edad { get; set; }
        public double peso { get; set; }
        public bool sexo { get; set; }
    }
}

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Controllers/Operaciones1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab01.MVC_Hinojosa.Models;

namespace Lab01.MVC_Hinojosa.Controllers
{
    public class Operaciones1Controller : Controller
    {
        // GET: Operaciones1
        ClsOperaciones operacion = new ClsOperaciones();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calcular()
        {
            //Recepcionar las variables
            operacion.numero1 = Convert.ToDouble(Request.Form["valor1"]);
            operacion.numero2 = Convert.ToDouble(Request.Form["valor2"]);
            operacion.tipo = Request.Form["tipo"];

            if (operacion.tipo.Equals("S"))
            {
                operacion.resultado = operacion.numero1 + operacion.numero2;
            }

            else if (operacion.tipo.Equals("R"))
            {
                operacion.resultado = operacion.numero1 - operacion.numero2;
            }

            else if (operacion.tipo.Equals("M"))
            {
                operacion.resultado = operacion.numero1 * operacion.numero2;
            }

            else
            {
                if (operacion.numero2 != 0)
                {
                    operacion.resultado = operacion.numero1 / operacion.numero2;
                }
                
            }

            return View(operacion);
        }
    }
}

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Controllers/Operaciones2Controller.cs
using Lab01.MVC_Hinojosa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace Lab01.MVC_Hinojosa.Controllers
{
    public class Operaciones2Controller : Controller
    {
        // GET: Operaciones2
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calcular(ClsOperaciones operacion) 
        {

            if (operacion.tipo.Equals("S"))
            {
                operacion.resultado = operacion.numero1 + operacion.numero2;
            }

            else if (operacion.tipo.Equals("R"))
            {
                operacion.resultado = operacion.numero1 - operacion.numero2;
            }

            else if (operacion.tipo.Equals("M"))
            {
                operacion.resultado = operacion.numero1 * operacion.numero2;
            }

            else
            {
                if (operacion.numero2 != 0)
                {
                    operacion.resultado = operacion.numero1 / operacion.numero2;
                }

            }

            return View(operacion);
        }
    }
}

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab01.MVC_Hinojosa.Models;

namespace Lab01.MVC_Hinojosa.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            ClsPersona persona = new ClsPersona();
            persona.apellido = "Christian Hinojosa";
            persona.nombres = "Christian Hinojosa";
            persona.email = "christian@gmail.com";
            persona.edad = 25;
            persona.peso = 89.99;
            persona.sexo= false;

            //return View("Index", persona);
            return View(persona);
        }
    }
}

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Views/operaciones1/Calcular.cshtml
@model Lab01.MVC_Hinojosa.Models.ClsOperaciones
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calcular</title>
</head>
<body>
    <div>
        <center>
            <h1>Operaciones Aritmeticas</h1>
            <br /><br />
            <label>Numero 1: </label>@Model.numero1 <br />
            <label>Numero 2: </label>@Model.numero2 <br />
            <label>Operacion: </label>@Model.tipo <br />
            <br />
            <label>Resultado: </label>@Model.resultado
            <br /><br />
            <a href="Index"><< Retornar al formulario</a>
            <br /><br />
        </center>
    </div>
</body>
</html>

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Views/operaciones1/Index.cshtml
@model Lab01.MVC_Hinojosa.Models.ClsOperaciones
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <center>
            <h1>Operaciones Aritmeticas</h1>
            <br />
            <form name="frmOperaciones" action="Calcular" method="post">
                <label>Numero 1: </label>
                <input type="number" name="valor1" /> <br />
                <label>Numero 2: </label>
                <input type="number" name="valor2" /> <br />
                <label>Operación: </label>
                <select name="tipo">
                    <option value="S">Suma</option>
                    <option value="R">Resta</option>
                    <option value="M">Multiplicacion</option>
                    <option value="D">División</option>
                </select>
                <br />
                <input type="submit" value="Calcular" /> <br />
            </form>
            <br />
        </center>

    </div>
</body>
</html>

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Views/operaciones2/Calcular.cshtml
@model Lab01.MVC_Hinojosa.Models.ClsOperaciones
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calcular</title>
</head>
<body>
    <div>
        <center>
            <h1>Operaciones Aritmeticas</h1>
            <br /><br />
            <label>Numero 1: </label>@Model.numero1 <br />
            <label>Numero 2: </label>@Model.numero2 <br />
            <label>Operacion: </label>@Model.tipo <br />
            <br />
            <label>Resultado: </label>@Model.resultado
            <br /><br />
            <a href="Index"><< Retornar al formulario</a>
            <br /><br />
        </center>
    </div>
</body>
</html>

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Views/operaciones2/Index.cshtml
@model Lab01.MVC_Hinojosa.Models.ClsOperaciones
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <center>
            <h1>Operaciones Aritmeticas = Razor</h1>
            <br /><br />
            @using (Html.BeginForm("Calcular", "Operaciones2", FormMethod.Post))
            {
                <div>
                    @Html.Label("Numero 1: ")
                    @Html.EditorFor(model => model.numero1)
                </div>
                <br />
                <div>
                    @Html.LabelFor(model => Model.numero2, "Numero 2: ")
                    @Html.EditorFor(model => model.numero2)
                </div>
                <br />
                <div>
                    @Html.LabelFor(model => Model.tipo, "Operaciones: ")
                    @Html.DropDownListFor(model => model.tipo, new List<SelectListItem>
                    {
                        new SelectListItem() { Text = "Suma", Value = "S"},
                        new SelectListItem() { Text = "Resta", Value = "R"},
                        new SelectListItem() { Text = "Multiplicacion", Value = "M"},
                        new SelectListItem() { Text = "Division", Value = "D"}
                    })
                </div>
                <br />
                <input type="submit" value="= "Calcular" />
             }
            <br /><br />
        </center>
    </div>
</body>
</html>

Laboratorios_Unidad1/Lab01.MVC_Hinojosa/Lab01.MVC_Hinojosa/Views/persona/Index.cshtml
@model Lab01.MVC_Hinojosa.Models.ClsPersona
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>Datos Personales</h1>
        <div>
            <label>Apellidos: </label>@Model.apellido <br />
            <label>Nombres: </label>@Model.nombres <br />
            <label>Email: </label>@Model.email <br />
            <label>Edad: </label>@Model.edad <br />
            <label>Peso: </label>@Model.peso <br />
            <label>Sexo: </label>@(Model.sexo.Equals(true) ? "Masculino" : "Femenino")
        </div>
    </div>
</body>
</html>