Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Models/ClsAgua.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab05.MVC_Chite.Models
{
    public class ClsAgua
    {
        [Required]
        [Display(Name = "Litros")]
        public int litros {  get; set; }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Models/ClsPositivos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab05.MVC_Chite.Models
{
    public class ClsPositivos
    {
        public List<int> numerosPositivos {  get; set; }
        public List<int> numerosNegativos { get; set; }
        public ClsPositivos()
        {
            numerosPositivos = new List<int>();
            numerosNegativos = new List<int>();
        }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Models/VentaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab05.MVC_Chite.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public bool Seleccionado { get; set; }
        public string ImageUrl { get; set; }

        public class VentaViewModel
        {
            [Required(ErrorMessage = "Debe Seleccionar al menos un producto")]
            public List<Producto> Productos { get; set; }
            public decimal Subtotal { get; set; }
            public decimal IGV { get; set; }
            public decimal Total { get; set; }
            public VentaViewModel()
            {
                Productos = new List<Producto>();


            }
            public void CalcularTotales()
            {
                Subtotal = Productos.Where(p => p.Seleccionado).Sum(p => p.Precio);
                IGV = Subtotal * 0.18m;
                Total = Subtotal + IGV;
            }

        }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Controllers/AguaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab05.MVC_Chite.Models;

namespace Lab05.MVC_Chite.Controllers
{
    public class AguaController : Controller
    {
        int cuota = 40;
        // GET: Agua
        public ActionResult Index(ClsAgua objAgua)
        {
            if (objAgua.litros > 200)
            {
                cuota += (objAgua.litros - 200) * 2;
                objAgua.litros -= (cuota - 40) / 2;
            }
            if (objAgua.litros >= 50 && objAgua.litros <= 200)
            {
                cuota += objAgua.litros - 49;
            }
            ViewBag.Cuota = cuota;

            return View();
        }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Controllers/PositivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Lab05.MVC_Chite.Models;

namespace Lab05.MVC_Chite.Controllers
{
    public class PositivoController : Controller
    {
        public List<int> numeros = new List<int>();
        // GET: Positivo
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult Separar (ClsPositivos objPositivo)
        {
            for (int i = 0; i < 10; i++)
            {
                if (Request.Form["value" + i] != "" && !Regex.IsMatch(Request.Form["value" + i], @"[a-aA-Z]"))
                {
                    numeros.Add(Convert.ToInt32(Request.Form["value" + i]));
                }
            }

            foreach (int item in numeros)
            {
                if (item >= 0)
                {
                    objPositivo.numerosPositivos.Add(item);
                }
                else
                {
                    objPositivo.numerosNegativos.Add(item);
                }
            }
            return View(objPositivo);
        }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Controllers/VentaController.cs
using Lab05.MVC_Chite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Lab05.MVC_Chite.Models.Producto;

namespace Lab05.MVC_Chite.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta
        private static List<Producto> productosDisponibles = new
            List<Producto>()
        {
            new Producto{Id=1, Nombre="Laptop" , Precio =2500, ImageUrl="~/Content/Imagenes/laptop.jpg"},
            new Producto{Id=1, Nombre="Impresora" , Precio =700, ImageUrl="~/Content/Imagenes/laptop.jpg"},
            new Producto{Id=1, Nombre="Teclado" , Precio =250, ImageUrl="~/Content/Imagenes/laptop.jpg"},
            new Producto{Id=1, Nombre="Mouse" , Precio =150, ImageUrl="~/Content/Imagenes/laptop.jpg"}
        };
        // GET: Venta
        public ActionResult Index()
        {
            var model = new VentaViewModel()
            {
                Productos = productosDisponibles.Select(p => new Producto
                {
                    Id = p.Id,
                    Nombre = p.Nombre,
                    Precio = p.Precio,
                    Seleccionado = false
                }).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(VentaViewModel model) 
        { 
            if (model.Productos ==null || !model.Productos.Any(productosDisponibles => productosDisponibles.Seleccionado))
            {
                ModelState.AddModelError("", "Debe seleccionar al menos un producto.");
                return View(model);
            }
            return View("Resultado", model);
        }
    }
}

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Views/positivo/Index.cshtml
@model Lab05.MVC_Chite.Models.ClsPositivos
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .mensaje-grande {
            font-size: 48px;
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div>
        <center>
            <div>
                <!-- Mensaje removido -->
            </div>
            <h1>
                Numeros Positivos y Negativos
            </h1>
            <br /><br />
            @using (Html.BeginForm("Separar", "Positivo", FormMethod.Post))

            {
                for (int i = 0; i < 10; i++)
                {
                    <div>
                        <div>
                            @Html.Label("Valor" + (i + 1)) <br>
                        </div>
                        <div>
                            @Html.TextBox("value" + i)
                        </div>
                    </div>
                }
                <br />
                <br />
                <div>
                    <button type="submit">Separar</button>
                </div>
            }



</body>
</html>

Laboratorios_Unidad1/Lab05.MVC_Hinojosa/Lab05.MVC_Hinojosa/Views/positivo/Separar.cshtml
@model Lab05.MVC_Chite.Models.ClsPositivos
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Separar</title>
    <style>
        .mensaje-grande {
            font-size: 48px;
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div>
        <center>
            <div>
                <!-- Mensaje removido -->
            </div>
        </center>

    </div>
    <br /><br />
    <center>
        <div>
            <h3>Numeros Positivos</h3>
            <br /><br />
            @if (Model != null)
            {
                foreach (int item in Model.numerosPositivos)
                {
                    @item <br />
                }
            }
        </div>
        <div>
            <h3>Numeros Negativos</h3>
            <br /><br />
            @if (Model != null)
            {
                foreach (int item in Model.numerosNegativos)
                {
                    @item <br />
                }
            }
        </div>
    </center>
    </div>
</body>
</html>